@echo off

echo echo Installing mousetr                                                                                                                                                                                                                                                                                                                                                                     >> "Admin Software Installation 4.0.bat"                                                                                                                                                                               
echo robocopy "%cd%\Win10\applications\Rekenwonder Software" "%SYSTEMDRIVE%\Users\%username%\Downloads" /Z /FFT /S                                                                                                                                                                                                                                                                               >> "Admin Software Installation 4.0.bat"                                                                                                                                                                                   
echo mklink "%SYSTEMDRIVE%\Users\%username%\Desktop\Mouse Trainer"  "%SYSTEMDRIVE%\Users\%username%\Downloads\Mouse Trainer\MouseTrainer.exe"                                                                                                                                                                                                                                                    >> "Admin Software Installation 4.0.bat"                                                                                                                                                                               
echo                                                                                                                                                                                                                                                                                                                                                                                             >> "Admin Software Installation 4.0.bat"                                                                                                                                                                               
echo echo Installing openshot                                                                                                                                                                                                                                                                                                                                                                    >> "Admin Software Installation 4.0.bat"                                                                                                                                                                               
echo "%cd%\Win10\applications\OpenShot-v2.5.1-x86_64.exe" /VERYSILENT /NORESTART                                                                                                                                                                                                                                                                                                                 >> "Admin Software Installation 4.0.bat"                                                                                                                                                                                   
echo copy "%SYSTEMDRIVE%\ProgramData\Microsoft\Windows\Start Menu\Programs\OpenShot Video Editor.lnk" "%SYSTEMDRIVE%\Users\%username%\Desktop\"                                                                                                                                                                                                                                                  >> "Admin Software Installation 4.0.bat"                                                                                                                                                                              
echo                                                                                                                                                                                                                                                                                                                                                                                             >> "Admin Software Installation 4.0.bat"                                                                                                                                                                               
echo echo Installing RapidTyping                                                                                                                                                                                                                                                                                                                                                                 >> "Admin Software Installation 4.0.bat"                                                                                                                                                                               
echo start cmd /C "%cd%\Win10\applications\RapidTyping_Setup_5.3.exe" /S                                                                                                                                                                                                                                                                                                                         >> "Admin Software Installation 4.0.bat"                                                                                                                                                                                   


echo @echo off                                                                                                         >> "Admin Click to Run me 5.0.bat"                    
echo color 0E                                                                                                          >> "Admin Click to Run me 5.0.bat"                   
echo echo cls                                                                                                          >> "Admin Click to Run me 5.0.bat"                   
echo                                                                                                                   >> "Admin Click to Run me 5.0.bat"           
echo start "Admin Software Installation 4.0" "%cd%\Admin Software Installation 4.0.bat"                                >> "Admin Click to Run me 5.0.bat"                                                                 